version: "2"

services:
  vote:
    build: .
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    environment:
      - "CONSUL_HOST=localhost"

  redis:
    image: redis:alpine
    ports: ["6379"]

